apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: jev-observability-stack
spec:
  project: default
  source:
    repoURL: https://github.com/nikhil-pagote/jev.git
    targetRevision: HEAD
    path: argocd-apps/kong/chart
    helm:
      valueFiles:
        - ../values/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
