apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: jev-observability-stack
spec:
  project: default
  source:
    repoURL: https://github.com/nikhil-pagote/jev.git
    targetRevision: HEAD
    path: argocd-apps/grafana/chart
    helm:
      valueFiles:
        - ../values/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
